### ISSUE TITLE
Depth Measurement

### ISSUE THREAD

**Issue by dommy1C** [MiaoDX/ZED_EmguCV#1]
Hi,
Trying to find a depth camera for my needs.  I use C# and EmguCv so this looks like a good place to see what wrappers there are available for the Zed cameras.

Is there anywhere in this code that wil give me the distance between camera and surrounding areas?

thanks

**Comment by MiaoDX** [comment]
Hi, I no longer have my windows PC anymore, but this project was (should) tested before, try to use it as shown in README.

The ZED camera can acquire depth images with `uint16` format easily, as shown at [ZED_Emgu/Program.cs#L47](https://github.com/MiaoDX/ZED_EmguCV/blob/master/ZED_Emgu/Program.cs#L47).

**Comment by dommy1C** [comment]
Thank you :)
