### ISSUE TITLE
DLL not found

### ISSUE THREAD

**Issue by dommy1C** [MiaoDX/ZED_EmguCV#2]
Hi,
I copied the DLLs to my solution and set the build to copy always.

When running the app I get:

```
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'sl_unitywrapper': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=ZED_Emgu
  StackTrace:
   at sl.ZEDCamera.dllz_get_sdk_version()
   at sl.ZEDCamera.GetSDKVersion() in C:\Users\Andrew\Downloads\ZED_EmguCV-master\ZED_Emgu\NativeInterface\ZEDCamera.cs:line 1171
   at ZedTester.Form1..ctor() in C:\Users\Andrew\Downloads\ZED_EmguCV-master\ZedTester\Form1.cs:line 24
   at ZedTester.Program.Main() in C:\Users\Andrew\Downloads\ZED_EmguCV-master\ZedTester\Program.cs:line 18
```

This is my bin folder:

![zed](https://user-images.githubusercontent.com/7067386/54602203-f1fca080-4a38-11e9-963d-5be5bd29af4c.jpg)

**Comment by dommy1C** [comment]
[sl_unitywrapper.zip](https://github.com/MiaoDX/ZED_EmguCV/files/2983014/sl_unitywrapper.zip)

This is what it looks like in dependency wallker...

**Comment by MiaoDX** [comment]
Hi, seems to me there can be mistakes at adding the DLL into the project?
Or, maybe have a look at the [issue where I found this plugin](https://github.com/stereolabs/zed-unity/issues/15) and my last comment there about the SDK version?
Still, I graduated and no longer have one Windows system anymore, so try again and find one teammate to figure out the problem together ^_^

**Comment by dommy1C** [comment]
Thanks. Well done for graduating,  All the best :)
